// Package httpapi is a bounded authenticated transport over the existing search service.
package httpapi

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"mime"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/johan-larp/agentsearch/internal/analysis"
	"github.com/johan-larp/agentsearch/internal/app"
	"github.com/johan-larp/agentsearch/internal/config"
	"github.com/johan-larp/agentsearch/internal/diagnostics"
	"github.com/johan-larp/agentsearch/internal/models"
	"github.com/johan-larp/agentsearch/internal/report"
	"github.com/johan-larp/agentsearch/internal/security"
	"github.com/johan-larp/agentsearch/internal/sources"
	"github.com/johan-larp/agentsearch/internal/sources/hibp"
)

// Searcher is the existing runner-shaped, source-neutral application boundary.
type Searcher interface {
	Search(context.Context, models.Target, sources.Emit) error
}
type Handler struct {
	analyzer    *analysis.Service
	readTimeout time.Duration
	searcher    Searcher
	tokenHash   [32]byte
	timeout     time.Duration
	admission   chan struct{}
	log         *slog.Logger
}

// New consumes the bootstrap bearer token. Only its digest is retained for comparison.
func New(searcher Searcher, token security.Secret, cfg config.ServerConfig, logger *slog.Logger, analyzers ...*analysis.Service) (*Handler, error) {
	defer token.Destroy()
	if searcher == nil || cfg.Validate() != nil {
		return nil, errors.New("invalid HTTP service configuration")
	}
	h := &Handler{searcher: searcher, timeout: cfg.RequestTimeout, readTimeout: cfg.ReadTimeout, admission: make(chan struct{}, cfg.MaxConcurrent), log: logger}
	if len(analyzers) > 0 {
		h.analyzer = analyzers[0]
	}
	if h.log == nil {
		h.log = slog.Default()
	}
	err := token.Consume(func(b []byte) error {
		if len(b) < 32 || len(b) > 4096 {
			return errors.New("bearer token must contain 32 to 4096 printable non-space ASCII bytes")
		}
		for _, c := range b {
			if c < 33 || c > 126 {
				return errors.New("invalid bearer token format")
			}
		}
		h.tokenHash = sha256.Sum256(b)
		return nil
	})
	if err != nil {
		return nil, errors.New("valid API bearer token required from the configured environment variable")
	}
	return h, nil
}

type apiError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}
type response struct {
	Report   *report.Report   `json:"report,omitempty"`
	Analysis *models.Analysis `json:"analysis,omitempty"`
	Results  []models.Result  `json:"results,omitempty"`
	Error    *apiError        `json:"error,omitempty"`
}
type writer struct {
	http.ResponseWriter
	status     int
	errorCode  string
	targetType models.TargetType
	summary    diagnostics.Summary
}

func (w *writer) Unwrap() http.ResponseWriter { return w.ResponseWriter }
func (w *writer) WriteHeader(status int) {
	if w.status == 0 {
		w.status = status
		w.ResponseWriter.WriteHeader(status)
	}
}
func (w *writer) Write(b []byte) (int, error) {
	if w.status == 0 {
		w.WriteHeader(200)
	}
	return w.ResponseWriter.Write(b)
}
func send(w http.ResponseWriter, status int, payload any) {
	b, e := json.Marshal(payload)
	if e != nil {
		status = 500
		b = []byte(`{"error":{"code":"internal_error","message":"response unavailable"}}`)
	}
	if state, ok := w.(*writer); ok {
		if e != nil {
			state.errorCode = "internal_error"
		} else if p, ok := payload.(response); ok && p.Error != nil {
			state.errorCode = p.Error.Code
		}
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_, _ = w.Write(append(b, '\n'))
}
func fail(w http.ResponseWriter, status int, code, message string) {
	send(w, status, response{Error: &apiError{Code: code, Message: message}})
}
func (h *Handler) authorized(r *http.Request) bool {
	values := r.Header.Values("Authorization")
	if len(values) != 1 || len(values[0]) > 4103 {
		return false
	}
	token, ok := strings.CutPrefix(values[0], "Bearer ")
	if !ok {
		return false
	}
	sum := sha256.Sum256([]byte(token))
	return subtle.ConstantTimeCompare(sum[:], h.tokenHash[:]) == 1
}
func (h *Handler) ServeHTTP(dst http.ResponseWriter, r *http.Request) {
	w := &writer{ResponseWriter: dst}
	start := time.Now()
	route := "unknown"
	// Generated by us, never copied from an incoming identifier or URL.
	var id [16]byte
	requestID := ""
	defer func() {
		if recover() != nil {
			fail(w, 500, "internal_error", "request failed")
		}
		outcome := w.diagnosticOutcome(r.Context())
		level := slog.LevelInfo
		if route == "health" && w.status == 200 {
			level = slog.LevelDebug
		}
		h.log.Log(r.Context(), level, "http request", "operation", "http_request", "request_id", requestID,
			"route", route, "method", diagnosticMethod(r.Method), "target_type", diagnostics.Target(w.targetType),
			"status", w.status, "duration_ms", time.Since(start).Milliseconds(), "outcome", outcome.Outcome,
			"error_category", outcome.Category, "active_searches", len(h.admission), "max_concurrent", cap(h.admission))
	}()
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	if _, e := rand.Read(id[:]); e != nil {
		fail(w, 500, "internal_error", "request failed")
		return
	}
	requestID = hex.EncodeToString(id[:])
	w.Header().Set("X-Request-ID", requestID)
	r = r.WithContext(diagnostics.WithLogger(r.Context(), h.log.With("request_id", requestID)))
	switch r.URL.Path {
	case "/health":
		route = "health"
		if r.Method != http.MethodGet {
			w.Header().Set("Allow", "GET")
			fail(w, 405, "method_not_allowed", "use GET")
			return
		}
		if r.URL.RawQuery != "" || r.URL.ForceQuery {
			fail(w, 400, "invalid_request", "query parameters are not accepted")
			return
		}
		send(w, 200, struct {
			Status string `json:"status"`
		}{"ok"})
	case "/api/v1/search":
		route = "search"
		if r.Method != http.MethodPost {
			w.Header().Set("Allow", "POST")
			fail(w, 405, "method_not_allowed", "use POST with a JSON body")
			return
		}
		if !h.authorized(r) {
			w.Header().Set("WWW-Authenticate", "Bearer")
			fail(w, 401, "unauthorized", "valid bearer token required")
			return
		}
		if r.URL.RawQuery != "" || r.URL.ForceQuery {
			fail(w, 400, "invalid_request", "query parameters are not accepted")
			return
		}
		h.search(w, r)
	default:
		fail(w, 404, "not_found", "endpoint not found")
	}
}

var errResultLimit = errors.New("result limit exceeded")

func (h *Handler) search(w *writer, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), h.timeout)
	defer cancel()
	defer r.Body.Close()
	if err := ctx.Err(); err != nil {
		if errors.Is(err, context.DeadlineExceeded) {
			fail(w, 504, "timeout", "search timed out")
		} else {
			fail(w, 408, "cancelled", "request cancelled")
		}
		return
	}
	select {
	case h.admission <- struct{}{}:
		defer func() { <-h.admission }()
		diagnostics.Logger(ctx).InfoContext(ctx, "http search admitted", "operation", "http_request", "outcome", "started", "active_searches", len(h.admission), "max_concurrent", cap(h.admission))
	default:
		w.Header().Set("Retry-After", "1")
		fail(w, 429, "too_many_requests", "server is busy")
		return
	}
	media, params, e := mime.ParseMediaType(r.Header.Get("Content-Type"))
	if e != nil || media != "application/json" || (params["charset"] != "" && !strings.EqualFold(params["charset"], "utf-8")) || r.Header.Get("Content-Encoding") != "" {
		fail(w, 415, "unsupported_media_type", "use uncompressed UTF-8 application/json")
		return
	}
	// Also bound slow body reads by the request deadline. ReadTimeout remains an
	// independent server limit. Test writers may not support deadline control.
	deadline := time.Now().Add(min(h.timeout, h.readTimeout))
	if requestDeadline, ok := ctx.Deadline(); ok && requestDeadline.Before(deadline) {
		deadline = requestDeadline
	}
	_ = http.NewResponseController(w).SetReadDeadline(deadline)
	r.Body = http.MaxBytesReader(w, r.Body, MaxBodyBytes)
	raw, e := io.ReadAll(r.Body)
	if e != nil {
		clear(raw)
		var large *http.MaxBytesError
		var timedOut interface{ Timeout() bool }
		if errors.As(e, &large) {
			fail(w, 413, "request_too_large", "request body exceeds limit")
		} else if errors.Is(ctx.Err(), context.DeadlineExceeded) || (errors.As(e, &timedOut) && timedOut.Timeout()) {
			fail(w, 408, "request_timeout", "request body timed out")
		} else if ctx.Err() != nil {
			fail(w, 408, "cancelled", "request body unavailable")
		} else {
			fail(w, 400, "invalid_request", "request body unavailable")
		}
		return
	}
	requestedAnalysis := false
	target, e := decodeRequest(raw, &requestedAnalysis) // clears encoded buffers before provider invocation
	if e != nil {
		fail(w, 400, "invalid_request", "invalid search request")
		return
	}
	w.targetType = target.Type()
	if target.Type().Sensitive() {
		defer target.Secret().Destroy()
	}
	rows := make([]models.Result, 0)
	limited := false
	searchStarted := time.Now()
	e = h.searcher.Search(ctx, target, func(r models.Result) error {
		if len(rows) >= 10000 {
			limited = true
			return errResultLimit
		}
		w.summary.Observe(r)
		rows = append(rows, r.Normalized())
		return nil
	})
	var provider *hibp.Error
	if errors.As(e, &provider) {
		w.summary.Observe(models.Result{Status: models.StatusError, Metadata: map[string]string{"error_kind": string(provider.Kind)}})
	}
	if limited {
		fail(w, 503, "result_limit", "configured search exceeds result limit")
		return
	}
	status, apiErr, retry := classify(ctx, e, rows)
	if retry != "" {
		w.Header().Set("Retry-After", retry)
	}
	// Keep normalized observations, but replace failing rows' diagnostic payloads.
	// Raw provider errors, paths, network details and arbitrary error metadata never
	// become HTTP errors. Successful provider payloads retain their existing model.
	for i, r := range rows {
		if r.Status == models.StatusError {
			rows[i] = models.Result{Source: r.Source, SourceType: r.SourceType, SiteName: r.SiteName, Target: r.Target, TargetType: r.TargetType, Status: models.StatusError, Duration: r.Duration, Error: "source lookup failed"}.Normalized()
		}
	}
	var interpretation *models.Analysis
	var canonical *report.Report
	if requestedAnalysis {
		result := analysis.Failed("input_too_large")
		snapshot, snapshotErr := report.New(target.Type(), target.String(), rows, report.Options{CreatedAt: searchStarted, Duration: time.Since(searchStarted), Partial: apiErr != nil})
		if snapshotErr == nil {
			result = h.analyzer.Analyze(ctx, snapshot)
			canonical, _ = snapshot.WithAnalysis(result)
		}
		interpretation = &result
	}
	if len(rows) == 0 && apiErr == nil {
		send(w, status, struct {
			Results  []models.Result  `json:"results"`
			Analysis *models.Analysis `json:"analysis,omitempty"`
			Report   *report.Report   `json:"report,omitempty"`
		}{rows, interpretation, canonical})
		return
	}
	send(w, status, response{Results: rows, Error: apiErr, Analysis: interpretation, Report: canonical})
}
func classify(ctx context.Context, err error, rows []models.Result) (int, *apiError, string) {
	failure := func(status int, code, message string) (int, *apiError, string) {
		return status, &apiError{Code: code, Message: message}, ""
	}
	if errors.Is(ctx.Err(), context.DeadlineExceeded) || errors.Is(err, context.DeadlineExceeded) {
		return failure(504, "timeout", "search timed out")
	}
	if errors.Is(ctx.Err(), context.Canceled) || errors.Is(err, context.Canceled) {
		return failure(408, "cancelled", "search cancelled")
	}
	if errors.Is(err, app.ErrSearchUnavailable) {
		return failure(503, "service_unavailable", "search type is unavailable")
	}
	// The dispatcher deliberately strips provider error chains. Its allowlisted
	// metadata is therefore needed as well as typed errors from direct runners.
	var provider *hibp.Error
	if errors.As(err, &provider) {
		metadata := map[string]string{"error_kind": string(provider.Kind)}
		if provider.RetryAfter > 0 {
			metadata["retry_after_seconds"] = strconv.FormatInt(int64((provider.RetryAfter-1)/time.Second)+1, 10)
		}
		rows = append(append([]models.Result(nil), rows...), models.Result{Status: models.StatusError, Metadata: metadata})
	}
	status := 200
	code := ""
	retry := uint64(0)
	for _, r := range rows {
		if r.Status != models.StatusError {
			continue
		}
		if status == 200 {
			status = 502
			code = "upstream_failure"
		}
		if r.SourceType == models.SourceLocal {
			status = 503
			code = "service_unavailable"
		}
		if seconds, e := strconv.ParseUint(r.Metadata["retry_after_seconds"], 10, 64); e == nil && seconds > retry {
			retry = seconds
		}
		switch r.Metadata["error_kind"] {
		case "rate_limited":
			status = 429
			code = "rate_limited"
		case "timeout":
			if status != 429 {
				status = 504
				code = "timeout"
			}
		case "cancelled":
			if status != 429 {
				status = 408
				code = "cancelled"
			}
		case "service_unavailable", "unauthorized", "forbidden", "missing_api_key":
			if status == 502 {
				status = 503
				code = "service_unavailable"
			}
		}
	}
	if status == 200 && err != nil {
		status = 502
		code = "upstream_failure"
	}
	if status == 200 {
		return 200, nil, ""
	}
	retryText := ""
	if retry > 0 {
		retryText = strconv.FormatUint(retry, 10)
	}
	return status, &apiError{Code: code, Message: "search could not be completed"}, retryText
}
